language: rust
sudo: false

env:
  global:
    - secure: SHCtDqsoyOQdkfv0Kt+piay/LaYAu+teod6CPt+st1sahehvnJwpu+54pYwi8BrF3ADZ2xay3cwKr9Tl9LOKMCAwLRaGU9CMyMi0t1/ngq2iivUdpbvQMVZvkKPeCQvHf8jHH9u16n6FAm8AL4EXAwIdu/bW58GbS+gsinnN3gg=

script:
  - cargo build --release --verbose
  - cargo test --verbose

after_script:
  - cargo doc --verbose
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
