language: rust
sudo: true

env:
  global:
    - secure: gq/9qUZ4jI4lD+8MsqCg1nPdSZsr0Dm8Fyhyd0UbulJecbZtfUZiS6d9ZTYJCpOHHFXgopxMLkFF1LIDGplKmjejOpGyBZQHtnFLtgVYgVp3metNt3T/GKdUwjLNo6/DYoOvauvWp9zdv7QCn6GG0xaZgm2dk7PY3rnCXZBNY+Y=

script:
  - cargo build --release --verbose
  - cargo test --verbose
  - cargo doc --verbose

after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
