language: rust
sudo: true

env:
  global:
    - secure: i7Sl5SstG3Ze4MDTHNrcvR77AVgDAOkgU69HPaVQmSg5MYjk6/hK8Fctx54f47O3fYec1vuxvVUdv8yBmQK7+93vRYloip33gbBdqPwzhqmqzL0V2kH7YY6ymx/lpfQ0Gbj6WxSrfd7BtWkcVHdVWh1SQwp2gVJuD4oPTIX1S7Q=

script:
  - cargo build --release --verbose
  - cargo test --verbose
  - cargo doc --verbose

after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
