language: rust
sudo: true

env:
  global:
    - secure: D0AkPgUQXHGgtgyQL6wgC7qZiodw9OXH5tJw7PerQTPUFe4ZsCDW1nhOzctKRXLDeEYZeDcYTFgTdwMi8jiyhFjgaaXQFI8pw3eZUBrJ9Mo0I3X/WzCSZDnbaPT9lLjv9FQGfZ8LZDkwnmf6gGF6FdlMuOSYIQXzIwEeZJvLD6w=

script:
  - cargo build --release --verbose
  - cargo test --verbose
  - cargo doc --no-deps

after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
