[package]

name = "glm"
version = "0.1.3"
authors = [
    "Che Kenan <chekenan@gmail.com>"
]

description = "GLSL mathematics for Rust."
keywords = ["glm", "math", "opengl", "glsl"]
license = "MIT"
repository = "https://github.com/dche/glm-rs/"

[dependencies]
rand = "*"

[dev-dependencies]
quickcheck = "*"
